# Generated by Django 3.0.7 on 2020-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_book',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_book',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_book',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Описание книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_book',
            field=models.FileField(blank=True, upload_to='pdf/', verbose_name='Ссылка pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_book',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название книги'),
        ),
    ]
